Added global DataPoint and OutputPoint
sinzlab/neuralpredictors pull request #187
Opened 2023-02-14 16:58 UTC by Mvystrcilova

Global `DataPoint` and `OutputPoint` were added in `TransformDataset` and `FileTreeDatasetBase` respectively to make them serializable for pickle. This was necessary to be able to use these datasets and set `num_workers` > 0 in `torch.utils.data.DataLoader`.

2023-02-14 18:26 UTC, mohammadbashiri requested changes

2023-02-14 18:26 UTC, mohammadbashiri commented on neuralpredictors/data/datasets/base.py
> +            global OutputPoint
Does this work? I thought that the named tuple itself should be available in the global context. Have you tested it?
Also, If `output_rename` is `None` then `self.data_point` is used (next line) which is also a named tuple and should again be available in the global context. Or am I missing something?

2024-03-07 12:53 UTC, Mvystrcilova commented
It is not deprecated I think, I just never actually fixed it. I would say it’s still worth fixing.


> On 7. 3. 2024, at 13:48, Polina Turishcheva ***@***.***> wrote:
> 
> 
> @Mvystrcilova <https://github.com/Mvystrcilova> is it still up to date? What about Mohammad's comments? (should we go forward with the PR or its deprecated?)
> 
> —
> Reply to this email directly, view it on GitHub <https://github.com/sinzlab/neuralpredictors/pull/187#issuecomment-1983438378>, or unsubscribe <https://github.com/notifications/unsubscribe-auth/AHSL5IEVG6OLAS5Q5VHNHSLYXBOYTAVCNFSM6AAAAAAU3Z45J6VHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMYTSOBTGQZTQMZXHA>.
> You are receiving this because you were mentioned.
>

2024-03-11 09:54 UTC, pollytur commented
PR closed as it was a long time ago. A new PR with the same idea would be great

2024-03-11 09:54 UTC, closed without merging