Add transforms, features, and Claudius PR
sinzlab/neuralpredictors pull request #95
Opened 2020-10-29 17:08 UTC by KonstantinWilleke

PR that has accumulated a bunch of small features.

- Scale transformation for the NeuroNormalizer in transforms.py
- solving a bug when normalizing the behavior states, and giving the eye_position the right name (pupil_center)
- adding a 5x5 laplace filter for the Laplace regularizer
- initializing a FileTree Dataset without behavior
- adding a new regularizer to the gaussian readout, that just returns the standard deviations of positions learned.

- Add the deterministic gaussian readout of Claudius

2020-10-29 18:05 UTC, KonstantinWilleke commented
This PR is a replacement for https://github.com/sinzlab/neuralpredictors/pull/89.
All issues that were mentioned there are addressed.

2020-10-30 21:50 UTC, eywalker requested changes

2020-10-30 21:50 UTC, eywalker commented on neuralpredictors/regularizers.py
> +def laplace5x5():
Where did the definition of these filters come from? It actually appears to LoG, not Laplace filters.

2020-10-30 21:50 UTC, eywalker commented on neuralpredictors/regularizers.py
> +    Returns a 5x5 laplace filter.
update this to say 7x7

2020-10-30 21:50 UTC, eywalker commented on neuralpredictors/data/transforms.py
> +        if "pupil_center" in data.data_keys:
make this work with either "pupil_center" or "eye_position" and not just overwrite. Static datasets use "pupil_center" and movie datasets are using "eye_position"

2020-10-30 21:50 UTC, eywalker commented on neuralpredictors/data/transforms.py
> +            threshold = 0.01 * s
this definition doesn't make sense as `s > 0.01 * s` is true all the time provided that `s` is a positive array (which it is as it's std values), so either completely get rid of this thresholding behavior, or come up with a meaningful thresholding scheme.

2020-10-30 21:50 UTC, eywalker commented on neuralpredictors/data/transforms.py
>              "responses": self.transforms["responses"](key_vals["responses"]),
why apply transforms given that `transforms` for `responses`, `behavior` and `pupile_center` are set as no-op. Do you expect these values to be overridden?

2021-03-29 17:37 UTC, eywalker approved these changes

2021-03-29 17:37 UTC, merged